name: Generate Snake

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Generate snake
      uses: Platane/snk@v2.2.1
      with:
        github_user_name: PhantHive
        svg_out_path: dist/github-contribution-grid-snake.svg
    - name: Commit generated snake
      run: |
        git config --global user.name "PhantHive"
        git config --global user.email "you@example.com"
        git add dist/github-contribution-grid-snake.svg
        git commit -m "Add snake contribution $(date)"
        git push
